import { Product } from "./ProductModal";

export const allProducts: Product[] = [
    // ─── LEHENGAS ─────────────────────────────────────────────────────────────
    {
        id: "leh-1",
        name: "The Mughal Vriksh Lehenga",
        category: "Lehengas",
        type: "Bridal Lehenga",
        fabric: "Crimson Silk Velvet & Organza",
        price: "₹4,80,000",
        description:
            "Adorned with ancient dabka needlework, seed pearls, and real gold wire zardozi. The skirt features a continuous tapestry of Mughal tree-of-life arches — 320 hours of meticulous handcraft on every piece.",
        details: [
            "320 hours of zardozi embroidery",
            "Pure silk velvet skirt with organza layers",
            "Gold wire and seed pearl work",
            "Custom fitting in 6–8 weeks",
            "Includes dupatta and unstitched blouse",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop",
        tag: "Bridal",
        rating: 5,
        reviews: 128,
    },
    {
        id: "leh-2",
        name: "The Basant Utsav Lehenga",
        category: "Lehengas",
        type: "Festive Lehenga",
        fabric: "Marigold Yellow Banarasi Silk",
        price: "₹2,65,000",
        description:
            "Handwoven in Varanasi using raw katan silk and floral buttis spun with pure gold metallic threads. A lightweight, fluid border that flows with every movement.",
        details: [
            "140 handloom hours",
            "Pure katan silk from Varanasi",
            "Real gold thread weave",
            "Natural dyes used",
            "Includes hand-embroidered blouse",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop",
        tag: "Bestseller",
        rating: 5,
        reviews: 94,
    },
    {
        id: "leh-3",
        name: "The Neelambari Lehenga",
        category: "Lehengas",
        type: "Reception Lehenga",
        fabric: "Midnight Indigo Raw Silk",
        price: "₹3,40,000",
        description:
            "Intricate silver and white gold zardozi borders mimicking constellations, paired with matching tissue dupatta and hand-spun Banarasi brocade blouse.",
        details: [
            "240 needlework hours",
            "Silver and white gold zardozi",
            "Tissue silk dupatta included",
            "Banarasi brocade blouse fabric",
            "Available in custom colours",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop",
        rating: 4,
        reviews: 67,
    },
    {
        id: "leh-4",
        name: "Rani Pink Floral Lehenga",
        category: "Lehengas",
        type: "Mehendi Lehenga",
        fabric: "Hot Pink Georgette",
        price: "₹1,65,000",
        description:
            "Hand-painted floral motifs on soft georgette, perfect for mehendi ceremonies and festive occasions. Light and breathable with a full flared skirt.",
        details: [
            "Hand-painted florals",
            "100% pure georgette",
            "Fully lined inner skirt",
            "Adjustable drawstring waist",
            "Available with or without blouse",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "/lehenga_pink.jpg",
        tag: "New In",
        rating: 4,
        reviews: 42,
    },

    // ─── SAREES ───────────────────────────────────────────────────────────────
    {
        id: "sar-1",
        name: "Scarlet Zardozi Silk Saree",
        category: "Sarees",
        type: "Bridal Saree",
        fabric: "Red Katan Silk",
        price: "₹2,45,000",
        originalPrice: "₹2,80,000",
        description:
            "A masterpiece in red katan silk with dense zardozi gold border work. The pallu features a garden of peacocks rendered in pure gold thread — a true heirloom piece.",
        details: [
            "Pure katan silk, Varanasi",
            "6.5 metres with matching blouse piece",
            "Real gold zardozi border (3 inch)",
            "Peacock motif hand-embroidered pallu",
            "Certificate of authenticity included",
        ],
        sizes: ["Standard (6.5m)", "Custom length"],
        imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop",
        tag: "Heritage",
        rating: 5,
        reviews: 211,
    },
    {
        id: "sar-2",
        name: "Midnight Velvet Saree",
        category: "Sarees",
        type: "Party Saree",
        fabric: "Black Silk Velvet",
        price: "₹1,85,000",
        description:
            "Dramatic black silk velvet saree with silver embroidery and sequin scattered pallu. The contemporary drape silhouette makes it ideal for receptions and gala evenings.",
        details: [
            "Premium silk velvet fabric",
            "Silver hand-embroidery on border",
            "Scatter sequin pallu",
            "Pre-stitched petticoat available",
            "Includes satin blouse piece",
        ],
        sizes: ["Standard (5.5m)", "Standard (6m)", "Custom"],
        imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop",
        tag: "Noir Edit",
        rating: 5,
        reviews: 88,
    },
    {
        id: "sar-3",
        name: "The Ivory Kanjivaram Saree",
        category: "Sarees",
        type: "Temple Saree",
        fabric: "Off-white Pure Silk",
        price: "₹3,10,000",
        description:
            "Woven over 15 days on traditional looms in Kanchipuram, this off-white silk saree features a deep gold zari border and temple motif pallu — an unmatched investment piece.",
        details: [
            "Handloom woven 15 days",
            "Pure mulberry silk",
            "22-carat gold zari",
            "Temple motif pallu",
            "GI-tagged Kanjivaram",
        ],
        sizes: ["Standard (6m)", "Custom"],
        imageUrl: "/saree_ivory.jpg",
        tag: "Investment Piece",
        rating: 5,
        reviews: 154,
    },
    {
        id: "sar-4",
        name: "Imperial Amethyst Silk Saree",
        category: "Sarees",
        type: "Royal Saree",
        fabric: "Purple Kanjivaram Silk",
        price: "₹3,10,000",
        description:
            "Deep purple Kanjivaram silk with contrasting gold border and silver thread work running through the body — regal, commanding, and utterly timeless.",
        details: [
            "Double-warp Kanjivaram silk",
            "Gold and silver mixed zari",
            "Traditional peacock motifs",
            "5.5 metres with matching blouse",
            "Hand-finished edges",
        ],
        sizes: ["Standard (5.5m)", "Standard (6m)"],
        imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800&auto=format&fit=crop",
        tag: "Royal Drape",
        rating: 4,
        reviews: 73,
    },

    // ─── TOPS ─────────────────────────────────────────────────────────────────
    {
        id: "top-1",
        name: "Structured Anarkali Top",
        category: "Tops",
        type: "Anarkali Top",
        fabric: "Cream Chanderi Silk",
        price: "₹65,000",
        description:
            "An architectural anarkali top in cream chanderi silk with subtle gold block printing. Pairs beautifully with straight trousers, palazzos, or sharara.",
        details: [
            "100% pure chanderi silk",
            "Hand block-printed gold motifs",
            "Concealed side zip",
            "Fully lined interior",
            "Side slits for ease of movement",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        imageUrl: "https://images.unsplash.com/photo-1618375531912-867984bdfd87?q=80&w=800&auto=format&fit=crop",
        tag: "New In",
        rating: 4,
        reviews: 38,
    },
    {
        id: "top-2",
        name: "Embroidered Silk Kurti",
        category: "Tops",
        type: "Kurti",
        fabric: "Ivory Pure Silk",
        price: "₹48,000",
        description:
            "Delicate ivory pure silk kurti with hand-embroidered neckline and cuffs in phulkari style. Versatile enough for daywear or elevated casual evenings.",
        details: [
            "Pure Mysore silk",
            "Hand embroidered collar & cuffs",
            "Phulkari motifs in multi-colour thread",
            "Button-down front",
            "Machine washable",
        ],
        sizes: ["XS", "S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop",
        rating: 4,
        reviews: 61,
    },
    {
        id: "top-3",
        name: "Velvet Jacket Kurta",
        category: "Tops",
        type: "Jacket Kurta",
        fabric: "Wine Velvet with Thread Work",
        price: "₹1,10,000",
        description:
            "A dramatic wine velvet jacket kurta with intricate zari thread-work across the chest and sleeves. The long silhouette creates a commanding, regal presence.",
        details: [
            "Premium silk velvet",
            "Gold and wine zari threadwork",
            "Mandarin collar",
            "Straight cut kurta beneath",
            "Handcrafted buttons",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=800&auto=format&fit=crop",
        tag: "Royal Drape",
        rating: 5,
        reviews: 29,
    },
    {
        id: "top-4",
        name: "Heritage Silk Blazer",
        category: "Tops",
        type: "Blazer",
        fabric: "Ivory Silk Dupion",
        price: "₹85,000",
        description:
            "Power dressing meets heritage craft. This ivory silk dupion blazer features hand-embroidered lapels and a structured silhouette built for the modern Indian woman.",
        details: [
            "Silk dupion with slight sheen",
            "Hand-embroidered lapels",
            "Two front pockets",
            "Fully lined in contrast silk",
            "Single button closure",
        ],
        sizes: ["XS", "S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop",
        tag: "Executive Edit",
        rating: 4,
        reviews: 45,
    },

    // ─── PALAZZOS / PLAZO ─────────────────────────────────────────────────────
    {
        id: "plz-1",
        name: "Gold Print Palazzo Set",
        category: "Plazo",
        type: "Palazzo Pants",
        fabric: "Champagne Silk Georgette",
        price: "₹55,000",
        description:
            "Wide-leg palazzo pants in champagne georgette with an all-over gold block-print pattern. Effortless, floaty, and endlessly elegant for festive or semi-formal occasions.",
        details: [
            "Pure georgette fabric",
            "Hand block-printed gold design",
            "Elasticated waistband",
            "Full length with side pockets",
            "Available as set with matching top",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=800&auto=format&fit=crop",
        tag: "New In",
        rating: 4,
        reviews: 52,
    },
    {
        id: "plz-2",
        name: "Power Palazzo Co-ord Set",
        category: "Plazo",
        type: "Co-ord Set",
        fabric: "Sand Linen Blend",
        price: "₹78,000",
        description:
            "A tailored linen blend palazzo co-ord set in warm sand tone — the perfect intersection of ethnic elegance and boardroom authority. Matching kurta and palazzo.",
        details: [
            "Premium linen-cotton blend",
            "Matching kurta and palazzo",
            "Subtle woven texture",
            "Side zip on kurta",
            "Pockets in palazzo",
        ],
        sizes: ["XS", "S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1618375531912-867984bdfd87?q=80&w=800&auto=format&fit=crop",
        tag: "Executive Edit",
        rating: 4,
        reviews: 33,
    },
    {
        id: "plz-3",
        name: "Violet Organza Gharara",
        category: "Plazo",
        type: "Gharara",
        fabric: "Violet Organza Silk",
        price: "₹1,85,000",
        description:
            "A show-stopping royal violet gharara in organza silk with flared bottoms heavily embroidered in silver thread. The definition of regal grandeur.",
        details: [
            "Pure organza silk",
            "Silver hand embroidery throughout",
            "Heavily flared bottoms",
            "Includes matching kurti and dupatta",
            "180 hours embroidery work",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "/violet_gharara.jpg",
        tag: "Royal Drape",
        rating: 5,
        reviews: 18,
    },
    {
        id: "plz-4",
        name: "Embroidered Sharara Set",
        category: "Plazo",
        type: "Sharara",
        fabric: "Emerald Green Georgette",
        price: "₹1,20,000",
        description:
            "Emerald green georgette sharara with dense gold tilla embroidery on the flare. The matching short kurta is finished with mirror work and sequin detailing.",
        details: [
            "Pure georgette sharara",
            "Dense gold tilla embroidery on flare",
            "Mirror and sequin work on kurta",
            "Includes silk dupatta",
            "Custom fitting available",
        ],
        sizes: ["XS", "S", "M", "L", "XL", "Custom"],
        imageUrl: "/sharara_emerald.jpg",
        tag: "New In",
        rating: 4,
        reviews: 24,
    },
];

export function getProductById(id: string): Product | undefined {
    return allProducts.find((p) => p.id === id);
}
